# Generated by Django 5.1.1 on 2024-10-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0012_user_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Paid', max_length=10),
        ),
    ]
