# Generated by Django 5.1.1 on 2024-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0013_payment_last_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_installment_month',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
