# Generated by Django 5.1.1 on 2024-10-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0014_user_current_installment_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_installment_month',
            new_name='installment_no',
        ),
    ]
