# Generated by Django 5.1.1 on 2024-10-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0015_rename_current_installment_month_user_installment_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='installment_no',
            new_name='installment_number',
        ),
    ]
